name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug
        run: |
          pwd
          ls -la
          find . -maxdepth 2

      - name: Deploy Website
        run: |
          sudo rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            ./spotify/ /var/www/html/

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
